#!/bin/bash
clear
fi

if [[ $USER != 'root' ]]; then
	echo "ขออภัยคุณต้องเรียกใช้งานนี้เป็น root"
	exit
fi

# get the VPS IP
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

if [ "$MYIP" = "" ]; then
	MYIP=$(wget -qO- ipv4.icanhazip.com)
fi

echo -e ""| lolcat
echo -e "==========[[-SERVER-PREMIUM-]]=========" | lolcat
echo -e " รายชื่อ ทั้งหมด " | lolcat
echo -e "=================[[]]================" | lolcat
echo -e "USERNAME              EXP DATE     " | lolcat
echo -e "=================[[]]================" | lolcat

while read expired
do
	AKUN="$(echo $expired | cut -d: -f1)"
	ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
	exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
	if [[ $ID -ge 1000 ]]; then
		printf "%-21s %2s\n" "$AKUN" "$exp"
	fi
done < /etc/passwd

JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"

echo -e "=================[[]]================" | lolcat
echo -e "ทั้งหมด : $JUMLAH user" | lolcat
echo -e "=================[[]]================" | lolcat
echo -e ""
echo -e "=================[[]]================" | lolcat

echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                       "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT        " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO                "| lolcat
echo -e "   Script by 097-026-7262                  "| lolcat
echo -e "===========================================" | lolcat
echo -e " "| lolcat
