#!/bin/bash
clear
fi
read -p "ป้อนชื่อบัญชีที่จะเปลี่ยนรหัสผ่าน: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "ป้อนรหัสผ่านใหม่สำหรับบัญชีนี้ $username: " password

clear
echo "Connecting to ocspanel.info..."
sleep 0.4
echo "กำลังดำเนินการ..."
sleep 0.3
echo "ดำเนินการเรียบร้อย..."
sleep 1
	egrep "^$username" /etc/passwd >/dev/null
    echo -e "$password\n$password" | passwd $username
  clear
echo -e ""
echo -e ""
echo -e ""
echo -e ""| lolcat
echo -e "|        ACCOUNT INFORMATION SSH      |" | boxes -d dog | lolcat
echo -e "============[[-SERVER-PREMIUM-]]===========" | lolcat
echo -e "รหัสผ่านของบัญชีนี้ ${blue}$username${NC} ดำเนินการเปลี่ยนเรียบร้อย."
  echo -e "รหัสผ่านใหม่สำหรับบัญชีนี้ ${blue}$username${NC} คือ ${red}$password${NC}"
echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                       "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT        " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO                "| lolcat
echo -e "   Script by 097-026-7262                  "| lolcat
echo -e "===========================================" | lolcat
fi
