#!/bin/bash
clear
fi
clear
echo "Please Wait..."
sleep 0.5
echo "Generating Account..."
sleep 0.5
echo "Generating Host..."
sleep 0.5
echo "Generating Username..."
sleep 0.5
echo "Generating Password..."
sleep 1
MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

username=trial
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo -e ""| lolcat
echo -e "|       NEW ACCOUNT INFORMATION SSH      |" | boxes -d dog | lolcat
echo -e "============[[-SERVER-PREMIUM-]]===========" | lolcat
  echo "------------------------------" | lolcat
  echo "   Host     : $MYIP" | lolcat
  echo "   Username : $username" | lolcat
  echo "   Password : $passrandom" | lolcat
  echo "   Port     : 22,80,109,143,443" | lolcat
  echo "------------------------------" | lolcat
  echo " "
  
else
  useradd trial
  usermod -s /bin/false trial
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo -e ""| lolcat
echo -e "|       NEW ACCOUNT INFORMATION SSH      |" | boxes -d dog | lolcat
echo -e "============[[-SERVER-PREMIUM-]]===========" | lolcat
  echo "------------------------------" | lolcat
  echo "   Host     : $MYIP" | lolcat
  echo "   Username : $username" | lolcat
  echo "   Password : $passrandom" | lolcat
  echo "   Port     : 22,80,109,143,443" | lolcat
  echo "------------------------------" | lolcat
  echo " "
echo -e "===========================================" | lolcat
echo -e "   Admin & Detail  :                       "| lolcat
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT        " | lolcat
echo -e "   HEREBIRD & OCSPANEL.INFO                "| lolcat
echo -e "   Script by 097-026-7262                  "| lolcat
echo -e "===========================================" | lolcat
fi
